# Copyright 2019 Shanghai JingDuo Information Technology co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

.PHONY: all

IMAGE_REPOSITORY_URL = reg.kpaas.io/kpaas
BUILD_NUMBER = $(shell git rev-parse --short HEAD)
BUILD_TAG := $(shell date +%Y%m%d%H%M%S)

all: build_cross

.PHONY: restful_doc

SED_PATH := $(shell which sed)
restful_doc:
	# swaggo need larger than 1.6
	swag init -g cli/restful/main.go -o pkg/restful/swaggerdocs
	if strings $(SED_PATH) | grep -q 'GNU'; then \
		$(SED_PATH) -i '/^\/\/ This file was generated by swaggo\/swag at/{n;d;}' pkg/restful/swaggerdocs/docs.go; \
		$(SED_PATH) -i '/^\/\/ This file was generated by swaggo\/swag at/d' pkg/restful/swaggerdocs/docs.go; \
	else \
		$(SED_PATH) -i '' '/^\/\/ This file was generated by swaggo\/swag at/{n;d;}' pkg/restful/swaggerdocs/docs.go; \
		$(SED_PATH) -i '' '/^\/\/ This file was generated by swaggo\/swag at/d' pkg/restful/swaggerdocs/docs.go; \
	fi

.PHONY: build_restful_local
build_restful_local: restful_doc
	mkdir -p builds/debug
	go build -o builds/debug/restful -ldflags '${EXTLDFLAGS}-X github.com/kpaas-io/kpaas/pkg/utils/version.VersionDev=build.$(BUILD_NUMBER)' github.com/kpaas-io/kpaas/cli/restful

.PHONY: build_restful_cross
build_restful_cross: restful_doc
	mkdir -p builds/release
	GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o builds/release/restful -ldflags '${EXTLDFLAGS}-X github.com/kpaas-io/kpaas/pkg/utils/version.VersionDev=build.$(BUILD_NUMBER)' github.com/kpaas-io/kpaas/cli/restful

.PHONY: run_restful
run_restful: build_restful_local
	builds/debug/restful

build_restful_image: build_restful_cross
	docker build -t $(IMAGE_REPOSITORY_URL)/kpaas:$(BUILD_TAG) -f builds/docker/Dockerfile .

push_restful_image: build_restful_image
	docker push $(IMAGE_REPOSITORY_URL)/kpaas:$(BUILD_TAG)

build_cross: build_restful_cross