// Code generated by protoc-gen-go. DO NOT EDIT.
// source: deploy_controller.proto

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	deploy_controller.proto

It has these top-level messages:
	Auth
	SSH
	Node
	Error
	TestConnectionRequest
	TestConnectionReply
	NodeCheckConfig
	CheckNodesRequest
	CheckNodesReply
	CheckItem
	ItemCheckResult
	NodeCheckResult
	GetCheckNodesResultRequest
	GetCheckNodesResultReply
	NodePortRange
	Keepalived
	Loadbalancer
	KubeAPIServerConnect
	ClusterConfig
	Taint
	NodeDeployConfig
	DeployRequest
	DeployReply
	GetDeployResultRequest
	DeployItem
	DeployItemResult
	GetDeployResultReply
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Auth struct {
	// type could be ["password", "privatekey"]
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	// credential stores the content of password or privatekey
	Credential string `protobuf:"bytes,2,opt,name=credential" json:"credential,omitempty"`
}

func (m *Auth) Reset()                    { *m = Auth{} }
func (m *Auth) String() string            { return proto.CompactTextString(m) }
func (*Auth) ProtoMessage()               {}
func (*Auth) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Auth) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Auth) GetCredential() string {
	if m != nil {
		return m.Credential
	}
	return ""
}

// SSH contains the ssh login info.
type SSH struct {
	Port uint32 `protobuf:"varint,1,opt,name=port" json:"port,omitempty"`
	Auth *Auth  `protobuf:"bytes,2,opt,name=auth" json:"auth,omitempty"`
}

func (m *SSH) Reset()                    { *m = SSH{} }
func (m *SSH) String() string            { return proto.CompactTextString(m) }
func (*SSH) ProtoMessage()               {}
func (*SSH) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SSH) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *SSH) GetAuth() *Auth {
	if m != nil {
		return m.Auth
	}
	return nil
}

// Node contains the node metadata info
type Node struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Ip   string `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	Ssh  *SSH   `protobuf:"bytes,3,opt,name=ssh" json:"ssh,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Node) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Node) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Node) GetSsh() *SSH {
	if m != nil {
		return m.Ssh
	}
	return nil
}

type Error struct {
	Reason     string `protobuf:"bytes,1,opt,name=reason" json:"reason,omitempty"`
	Detail     string `protobuf:"bytes,2,opt,name=detail" json:"detail,omitempty"`
	FixMethods string `protobuf:"bytes,3,opt,name=fixMethods" json:"fixMethods,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Error) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *Error) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *Error) GetFixMethods() string {
	if m != nil {
		return m.FixMethods
	}
	return ""
}

// TestConnectionRequest contains the request of node connection testing.
type TestConnectionRequest struct {
	Node *Node `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
}

func (m *TestConnectionRequest) Reset()                    { *m = TestConnectionRequest{} }
func (m *TestConnectionRequest) String() string            { return proto.CompactTextString(m) }
func (*TestConnectionRequest) ProtoMessage()               {}
func (*TestConnectionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TestConnectionRequest) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

// TestConnectionReply contains the result of node connection testing.
type TestConnectionReply struct {
	Passed bool   `protobuf:"varint,1,opt,name=passed" json:"passed,omitempty"`
	Err    *Error `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *TestConnectionReply) Reset()                    { *m = TestConnectionReply{} }
func (m *TestConnectionReply) String() string            { return proto.CompactTextString(m) }
func (*TestConnectionReply) ProtoMessage()               {}
func (*TestConnectionReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *TestConnectionReply) GetPassed() bool {
	if m != nil {
		return m.Passed
	}
	return false
}

func (m *TestConnectionReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

// NodeCheckConfig contains the pre-checking configuration for a node
type NodeCheckConfig struct {
	Node  *Node    `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
	Roles []string `protobuf:"bytes,2,rep,name=roles" json:"roles,omitempty"`
}

func (m *NodeCheckConfig) Reset()                    { *m = NodeCheckConfig{} }
func (m *NodeCheckConfig) String() string            { return proto.CompactTextString(m) }
func (*NodeCheckConfig) ProtoMessage()               {}
func (*NodeCheckConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *NodeCheckConfig) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *NodeCheckConfig) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

// CheckNodesRequest contains the request of node pre-checking.
type CheckNodesRequest struct {
	Configs []*NodeCheckConfig `protobuf:"bytes,1,rep,name=configs" json:"configs,omitempty"`
}

func (m *CheckNodesRequest) Reset()                    { *m = CheckNodesRequest{} }
func (m *CheckNodesRequest) String() string            { return proto.CompactTextString(m) }
func (*CheckNodesRequest) ProtoMessage()               {}
func (*CheckNodesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CheckNodesRequest) GetConfigs() []*NodeCheckConfig {
	if m != nil {
		return m.Configs
	}
	return nil
}

// CheckNodesReply contains the result of node pre-checking.
type CheckNodesReply struct {
	Acceptd bool   `protobuf:"varint,1,opt,name=acceptd" json:"acceptd,omitempty"`
	Err     *Error `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *CheckNodesReply) Reset()                    { *m = CheckNodesReply{} }
func (m *CheckNodesReply) String() string            { return proto.CompactTextString(m) }
func (*CheckNodesReply) ProtoMessage()               {}
func (*CheckNodesReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CheckNodesReply) GetAcceptd() bool {
	if m != nil {
		return m.Acceptd
	}
	return false
}

func (m *CheckNodesReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

// CheckItem is a check item of node pre-checking
type CheckItem struct {
	Name        string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
}

func (m *CheckItem) Reset()                    { *m = CheckItem{} }
func (m *CheckItem) String() string            { return proto.CompactTextString(m) }
func (*CheckItem) ProtoMessage()               {}
func (*CheckItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *CheckItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CheckItem) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// ItemCheckResult contains the pre-checking reuslt of an itme
type ItemCheckResult struct {
	Item   *CheckItem `protobuf:"bytes,1,opt,name=item" json:"item,omitempty"`
	Status string     `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	Err    *Error     `protobuf:"bytes,3,opt,name=err" json:"err,omitempty"`
	Logs   string     `protobuf:"bytes,4,opt,name=logs" json:"logs,omitempty"`
}

func (m *ItemCheckResult) Reset()                    { *m = ItemCheckResult{} }
func (m *ItemCheckResult) String() string            { return proto.CompactTextString(m) }
func (*ItemCheckResult) ProtoMessage()               {}
func (*ItemCheckResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ItemCheckResult) GetItem() *CheckItem {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *ItemCheckResult) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ItemCheckResult) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *ItemCheckResult) GetLogs() string {
	if m != nil {
		return m.Logs
	}
	return ""
}

// ItemCheckResult contains the pre-checking reuslt of a node
type NodeCheckResult struct {
	NodeName string             `protobuf:"bytes,1,opt,name=nodeName" json:"nodeName,omitempty"`
	Status   string             `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	Err      *Error             `protobuf:"bytes,3,opt,name=err" json:"err,omitempty"`
	Items    []*ItemCheckResult `protobuf:"bytes,4,rep,name=items" json:"items,omitempty"`
}

func (m *NodeCheckResult) Reset()                    { *m = NodeCheckResult{} }
func (m *NodeCheckResult) String() string            { return proto.CompactTextString(m) }
func (*NodeCheckResult) ProtoMessage()               {}
func (*NodeCheckResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *NodeCheckResult) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *NodeCheckResult) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *NodeCheckResult) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *NodeCheckResult) GetItems() []*ItemCheckResult {
	if m != nil {
		return m.Items
	}
	return nil
}

// GetCheckNodesResultRequest contains the request of getting nodes check result.
type GetCheckNodesResultRequest struct {
	WithLogs bool `protobuf:"varint,1,opt,name=withLogs" json:"withLogs,omitempty"`
}

func (m *GetCheckNodesResultRequest) Reset()                    { *m = GetCheckNodesResultRequest{} }
func (m *GetCheckNodesResultRequest) String() string            { return proto.CompactTextString(m) }
func (*GetCheckNodesResultRequest) ProtoMessage()               {}
func (*GetCheckNodesResultRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *GetCheckNodesResultRequest) GetWithLogs() bool {
	if m != nil {
		return m.WithLogs
	}
	return false
}

// GetCheckNodesResultReply contains the result of nodes check
type GetCheckNodesResultReply struct {
	Status string             `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Err    *Error             `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	Nodes  []*NodeCheckResult `protobuf:"bytes,3,rep,name=nodes" json:"nodes,omitempty"`
}

func (m *GetCheckNodesResultReply) Reset()                    { *m = GetCheckNodesResultReply{} }
func (m *GetCheckNodesResultReply) String() string            { return proto.CompactTextString(m) }
func (*GetCheckNodesResultReply) ProtoMessage()               {}
func (*GetCheckNodesResultReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *GetCheckNodesResultReply) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetCheckNodesResultReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *GetCheckNodesResultReply) GetNodes() []*NodeCheckResult {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type NodePortRange struct {
	From uint32 `protobuf:"varint,1,opt,name=from" json:"from,omitempty"`
	To   uint32 `protobuf:"varint,2,opt,name=to" json:"to,omitempty"`
}

func (m *NodePortRange) Reset()                    { *m = NodePortRange{} }
func (m *NodePortRange) String() string            { return proto.CompactTextString(m) }
func (*NodePortRange) ProtoMessage()               {}
func (*NodePortRange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *NodePortRange) GetFrom() uint32 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *NodePortRange) GetTo() uint32 {
	if m != nil {
		return m.To
	}
	return 0
}

type Keepalived struct {
	Vip              string `protobuf:"bytes,1,opt,name=vip" json:"vip,omitempty"`
	NetInterfaceName string `protobuf:"bytes,2,opt,name=netInterfaceName" json:"netInterfaceName,omitempty"`
}

func (m *Keepalived) Reset()                    { *m = Keepalived{} }
func (m *Keepalived) String() string            { return proto.CompactTextString(m) }
func (*Keepalived) ProtoMessage()               {}
func (*Keepalived) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *Keepalived) GetVip() string {
	if m != nil {
		return m.Vip
	}
	return ""
}

func (m *Keepalived) GetNetInterfaceName() string {
	if m != nil {
		return m.NetInterfaceName
	}
	return ""
}

type Loadbalancer struct {
	Ip   string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Port uint32 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *Loadbalancer) Reset()                    { *m = Loadbalancer{} }
func (m *Loadbalancer) String() string            { return proto.CompactTextString(m) }
func (*Loadbalancer) ProtoMessage()               {}
func (*Loadbalancer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *Loadbalancer) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Loadbalancer) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

// KubeAPIServerConnect contains the info of how to connect to k8s API server
type KubeAPIServerConnect struct {
	// type could be ["firstMasterIP", "keepalived", "loadbalancer"]
	Type         string        `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Keepalived   *Keepalived   `protobuf:"bytes,2,opt,name=keepalived" json:"keepalived,omitempty"`
	Loadbalancer *Loadbalancer `protobuf:"bytes,3,opt,name=loadbalancer" json:"loadbalancer,omitempty"`
}

func (m *KubeAPIServerConnect) Reset()                    { *m = KubeAPIServerConnect{} }
func (m *KubeAPIServerConnect) String() string            { return proto.CompactTextString(m) }
func (*KubeAPIServerConnect) ProtoMessage()               {}
func (*KubeAPIServerConnect) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *KubeAPIServerConnect) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *KubeAPIServerConnect) GetKeepalived() *Keepalived {
	if m != nil {
		return m.Keepalived
	}
	return nil
}

func (m *KubeAPIServerConnect) GetLoadbalancer() *Loadbalancer {
	if m != nil {
		return m.Loadbalancer
	}
	return nil
}

// ClusterConfig contains the configuraton of a cluster
type ClusterConfig struct {
	ClusterName          string                `protobuf:"bytes,1,opt,name=clusterName" json:"clusterName,omitempty"`
	KubeAPIServerConnect *KubeAPIServerConnect `protobuf:"bytes,2,opt,name=kubeAPIServerConnect" json:"kubeAPIServerConnect,omitempty"`
	NodePortRange        *NodePortRange        `protobuf:"bytes,3,opt,name=nodePortRange" json:"nodePortRange,omitempty"`
	NodeLabels           map[string]string     `protobuf:"bytes,4,rep,name=nodeLabels" json:"nodeLabels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NodeAnnotations      map[string]string     `protobuf:"bytes,5,rep,name=nodeAnnotations" json:"nodeAnnotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ImageRepository      string                `protobuf:"bytes,6,opt,name=imageRepository" json:"imageRepository,omitempty"`
	PodSubnet            string                `protobuf:"bytes,7,opt,name=podSubnet" json:"podSubnet,omitempty"`
	ServiceSubnet        string                `protobuf:"bytes,8,opt,name=serviceSubnet" json:"serviceSubnet,omitempty"`
	KubernetesVersion    string                `protobuf:"bytes,9,opt,name=kubernetesVersion" json:"kubernetesVersion,omitempty"`
}

func (m *ClusterConfig) Reset()                    { *m = ClusterConfig{} }
func (m *ClusterConfig) String() string            { return proto.CompactTextString(m) }
func (*ClusterConfig) ProtoMessage()               {}
func (*ClusterConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *ClusterConfig) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *ClusterConfig) GetKubeAPIServerConnect() *KubeAPIServerConnect {
	if m != nil {
		return m.KubeAPIServerConnect
	}
	return nil
}

func (m *ClusterConfig) GetNodePortRange() *NodePortRange {
	if m != nil {
		return m.NodePortRange
	}
	return nil
}

func (m *ClusterConfig) GetNodeLabels() map[string]string {
	if m != nil {
		return m.NodeLabels
	}
	return nil
}

func (m *ClusterConfig) GetNodeAnnotations() map[string]string {
	if m != nil {
		return m.NodeAnnotations
	}
	return nil
}

func (m *ClusterConfig) GetImageRepository() string {
	if m != nil {
		return m.ImageRepository
	}
	return ""
}

func (m *ClusterConfig) GetPodSubnet() string {
	if m != nil {
		return m.PodSubnet
	}
	return ""
}

func (m *ClusterConfig) GetServiceSubnet() string {
	if m != nil {
		return m.ServiceSubnet
	}
	return ""
}

func (m *ClusterConfig) GetKubernetesVersion() string {
	if m != nil {
		return m.KubernetesVersion
	}
	return ""
}

type Taint struct {
	Key    string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value  string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	Effect string `protobuf:"bytes,3,opt,name=effect" json:"effect,omitempty"`
}

func (m *Taint) Reset()                    { *m = Taint{} }
func (m *Taint) String() string            { return proto.CompactTextString(m) }
func (*Taint) ProtoMessage()               {}
func (*Taint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *Taint) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Taint) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Taint) GetEffect() string {
	if m != nil {
		return m.Effect
	}
	return ""
}

// NodeDeployConfig contains the deploy configuration for a node
type NodeDeployConfig struct {
	Node *Node `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
	// role cloud be ["etcd", "master", "worker", ...]
	Roles  []string          `protobuf:"bytes,2,rep,name=roles" json:"roles,omitempty"`
	Labels map[string]string `protobuf:"bytes,3,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Taints []*Taint          `protobuf:"bytes,4,rep,name=taints" json:"taints,omitempty"`
}

func (m *NodeDeployConfig) Reset()                    { *m = NodeDeployConfig{} }
func (m *NodeDeployConfig) String() string            { return proto.CompactTextString(m) }
func (*NodeDeployConfig) ProtoMessage()               {}
func (*NodeDeployConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *NodeDeployConfig) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *NodeDeployConfig) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *NodeDeployConfig) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *NodeDeployConfig) GetTaints() []*Taint {
	if m != nil {
		return m.Taints
	}
	return nil
}

// DeployRequest contains the request of a deploy.
type DeployRequest struct {
	NodeConfigs   []*NodeDeployConfig `protobuf:"bytes,1,rep,name=nodeConfigs" json:"nodeConfigs,omitempty"`
	ClusterConfig *ClusterConfig      `protobuf:"bytes,2,opt,name=clusterConfig" json:"clusterConfig,omitempty"`
}

func (m *DeployRequest) Reset()                    { *m = DeployRequest{} }
func (m *DeployRequest) String() string            { return proto.CompactTextString(m) }
func (*DeployRequest) ProtoMessage()               {}
func (*DeployRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *DeployRequest) GetNodeConfigs() []*NodeDeployConfig {
	if m != nil {
		return m.NodeConfigs
	}
	return nil
}

func (m *DeployRequest) GetClusterConfig() *ClusterConfig {
	if m != nil {
		return m.ClusterConfig
	}
	return nil
}

// DeployReply contains the response of a deploy request.
type DeployReply struct {
	Acceptd bool   `protobuf:"varint,1,opt,name=acceptd" json:"acceptd,omitempty"`
	Err     *Error `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *DeployReply) Reset()                    { *m = DeployReply{} }
func (m *DeployReply) String() string            { return proto.CompactTextString(m) }
func (*DeployReply) ProtoMessage()               {}
func (*DeployReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *DeployReply) GetAcceptd() bool {
	if m != nil {
		return m.Acceptd
	}
	return false
}

func (m *DeployReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

// GetDeployResultRequest contains the request of getting deploy result.
type GetDeployResultRequest struct {
	WithLogs bool `protobuf:"varint,1,opt,name=withLogs" json:"withLogs,omitempty"`
}

func (m *GetDeployResultRequest) Reset()                    { *m = GetDeployResultRequest{} }
func (m *GetDeployResultRequest) String() string            { return proto.CompactTextString(m) }
func (*GetDeployResultRequest) ProtoMessage()               {}
func (*GetDeployResultRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *GetDeployResultRequest) GetWithLogs() bool {
	if m != nil {
		return m.WithLogs
	}
	return false
}

// DeployItem represents a deploy action in a node for a role.
type DeployItem struct {
	Role                string `protobuf:"bytes,1,opt,name=role" json:"role,omitempty"`
	NodeName            string `protobuf:"bytes,2,opt,name=nodeName" json:"nodeName,omitempty"`
	FailureCanBeIgnored bool   `protobuf:"varint,3,opt,name=failureCanBeIgnored" json:"failureCanBeIgnored,omitempty"`
}

func (m *DeployItem) Reset()                    { *m = DeployItem{} }
func (m *DeployItem) String() string            { return proto.CompactTextString(m) }
func (*DeployItem) ProtoMessage()               {}
func (*DeployItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *DeployItem) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *DeployItem) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *DeployItem) GetFailureCanBeIgnored() bool {
	if m != nil {
		return m.FailureCanBeIgnored
	}
	return false
}

// DeployItemResult represents the deploy result in a node for a role.
type DeployItemResult struct {
	DeployItem *DeployItem `protobuf:"bytes,1,opt,name=deployItem" json:"deployItem,omitempty"`
	Status     string      `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	Err        *Error      `protobuf:"bytes,3,opt,name=err" json:"err,omitempty"`
	Logs       string      `protobuf:"bytes,4,opt,name=logs" json:"logs,omitempty"`
}

func (m *DeployItemResult) Reset()                    { *m = DeployItemResult{} }
func (m *DeployItemResult) String() string            { return proto.CompactTextString(m) }
func (*DeployItemResult) ProtoMessage()               {}
func (*DeployItemResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *DeployItemResult) GetDeployItem() *DeployItem {
	if m != nil {
		return m.DeployItem
	}
	return nil
}

func (m *DeployItemResult) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *DeployItemResult) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *DeployItemResult) GetLogs() string {
	if m != nil {
		return m.Logs
	}
	return ""
}

// GetDeployResultReply represents the result of a deploy
type GetDeployResultReply struct {
	Status string              `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Err    *Error              `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	Items  []*DeployItemResult `protobuf:"bytes,3,rep,name=items" json:"items,omitempty"`
}

func (m *GetDeployResultReply) Reset()                    { *m = GetDeployResultReply{} }
func (m *GetDeployResultReply) String() string            { return proto.CompactTextString(m) }
func (*GetDeployResultReply) ProtoMessage()               {}
func (*GetDeployResultReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *GetDeployResultReply) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetDeployResultReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *GetDeployResultReply) GetItems() []*DeployItemResult {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*Auth)(nil), "protos.Auth")
	proto.RegisterType((*SSH)(nil), "protos.SSH")
	proto.RegisterType((*Node)(nil), "protos.Node")
	proto.RegisterType((*Error)(nil), "protos.Error")
	proto.RegisterType((*TestConnectionRequest)(nil), "protos.TestConnectionRequest")
	proto.RegisterType((*TestConnectionReply)(nil), "protos.TestConnectionReply")
	proto.RegisterType((*NodeCheckConfig)(nil), "protos.NodeCheckConfig")
	proto.RegisterType((*CheckNodesRequest)(nil), "protos.CheckNodesRequest")
	proto.RegisterType((*CheckNodesReply)(nil), "protos.CheckNodesReply")
	proto.RegisterType((*CheckItem)(nil), "protos.CheckItem")
	proto.RegisterType((*ItemCheckResult)(nil), "protos.ItemCheckResult")
	proto.RegisterType((*NodeCheckResult)(nil), "protos.NodeCheckResult")
	proto.RegisterType((*GetCheckNodesResultRequest)(nil), "protos.GetCheckNodesResultRequest")
	proto.RegisterType((*GetCheckNodesResultReply)(nil), "protos.GetCheckNodesResultReply")
	proto.RegisterType((*NodePortRange)(nil), "protos.NodePortRange")
	proto.RegisterType((*Keepalived)(nil), "protos.Keepalived")
	proto.RegisterType((*Loadbalancer)(nil), "protos.Loadbalancer")
	proto.RegisterType((*KubeAPIServerConnect)(nil), "protos.KubeAPIServerConnect")
	proto.RegisterType((*ClusterConfig)(nil), "protos.ClusterConfig")
	proto.RegisterType((*Taint)(nil), "protos.Taint")
	proto.RegisterType((*NodeDeployConfig)(nil), "protos.NodeDeployConfig")
	proto.RegisterType((*DeployRequest)(nil), "protos.DeployRequest")
	proto.RegisterType((*DeployReply)(nil), "protos.DeployReply")
	proto.RegisterType((*GetDeployResultRequest)(nil), "protos.GetDeployResultRequest")
	proto.RegisterType((*DeployItem)(nil), "protos.DeployItem")
	proto.RegisterType((*DeployItemResult)(nil), "protos.DeployItemResult")
	proto.RegisterType((*GetDeployResultReply)(nil), "protos.GetDeployResultReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DeployContoller service

type DeployContollerClient interface {
	TestConnection(ctx context.Context, in *TestConnectionRequest, opts ...grpc.CallOption) (*TestConnectionReply, error)
	CheckNodes(ctx context.Context, in *CheckNodesRequest, opts ...grpc.CallOption) (*CheckNodesReply, error)
	GetCheckNodesResult(ctx context.Context, in *GetCheckNodesResultRequest, opts ...grpc.CallOption) (*GetCheckNodesResultReply, error)
	Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployReply, error)
	GetDeployResult(ctx context.Context, in *GetDeployResultRequest, opts ...grpc.CallOption) (*GetDeployResultReply, error)
}

type deployContollerClient struct {
	cc *grpc.ClientConn
}

func NewDeployContollerClient(cc *grpc.ClientConn) DeployContollerClient {
	return &deployContollerClient{cc}
}

func (c *deployContollerClient) TestConnection(ctx context.Context, in *TestConnectionRequest, opts ...grpc.CallOption) (*TestConnectionReply, error) {
	out := new(TestConnectionReply)
	err := grpc.Invoke(ctx, "/protos.DeployContoller/TestConnection", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployContollerClient) CheckNodes(ctx context.Context, in *CheckNodesRequest, opts ...grpc.CallOption) (*CheckNodesReply, error) {
	out := new(CheckNodesReply)
	err := grpc.Invoke(ctx, "/protos.DeployContoller/CheckNodes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployContollerClient) GetCheckNodesResult(ctx context.Context, in *GetCheckNodesResultRequest, opts ...grpc.CallOption) (*GetCheckNodesResultReply, error) {
	out := new(GetCheckNodesResultReply)
	err := grpc.Invoke(ctx, "/protos.DeployContoller/GetCheckNodesResult", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployContollerClient) Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployReply, error) {
	out := new(DeployReply)
	err := grpc.Invoke(ctx, "/protos.DeployContoller/Deploy", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployContollerClient) GetDeployResult(ctx context.Context, in *GetDeployResultRequest, opts ...grpc.CallOption) (*GetDeployResultReply, error) {
	out := new(GetDeployResultReply)
	err := grpc.Invoke(ctx, "/protos.DeployContoller/GetDeployResult", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DeployContoller service

type DeployContollerServer interface {
	TestConnection(context.Context, *TestConnectionRequest) (*TestConnectionReply, error)
	CheckNodes(context.Context, *CheckNodesRequest) (*CheckNodesReply, error)
	GetCheckNodesResult(context.Context, *GetCheckNodesResultRequest) (*GetCheckNodesResultReply, error)
	Deploy(context.Context, *DeployRequest) (*DeployReply, error)
	GetDeployResult(context.Context, *GetDeployResultRequest) (*GetDeployResultReply, error)
}

func RegisterDeployContollerServer(s *grpc.Server, srv DeployContollerServer) {
	s.RegisterService(&_DeployContoller_serviceDesc, srv)
}

func _DeployContoller_TestConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployContollerServer).TestConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.DeployContoller/TestConnection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployContollerServer).TestConnection(ctx, req.(*TestConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployContoller_CheckNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployContollerServer).CheckNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.DeployContoller/CheckNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployContollerServer).CheckNodes(ctx, req.(*CheckNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployContoller_GetCheckNodesResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCheckNodesResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployContollerServer).GetCheckNodesResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.DeployContoller/GetCheckNodesResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployContollerServer).GetCheckNodesResult(ctx, req.(*GetCheckNodesResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployContoller_Deploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployContollerServer).Deploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.DeployContoller/Deploy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployContollerServer).Deploy(ctx, req.(*DeployRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployContoller_GetDeployResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeployResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployContollerServer).GetDeployResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.DeployContoller/GetDeployResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployContollerServer).GetDeployResult(ctx, req.(*GetDeployResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DeployContoller_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.DeployContoller",
	HandlerType: (*DeployContollerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestConnection",
			Handler:    _DeployContoller_TestConnection_Handler,
		},
		{
			MethodName: "CheckNodes",
			Handler:    _DeployContoller_CheckNodes_Handler,
		},
		{
			MethodName: "GetCheckNodesResult",
			Handler:    _DeployContoller_GetCheckNodesResult_Handler,
		},
		{
			MethodName: "Deploy",
			Handler:    _DeployContoller_Deploy_Handler,
		},
		{
			MethodName: "GetDeployResult",
			Handler:    _DeployContoller_GetDeployResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deploy_controller.proto",
}

func init() { proto.RegisterFile("deploy_controller.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x5b, 0x6f, 0x1b, 0xc5,
	0x17, 0xff, 0xaf, 0xed, 0xa4, 0xc9, 0x71, 0x5d, 0xa7, 0x93, 0xa4, 0xdd, 0xbf, 0x69, 0x4b, 0x34,
	0x6a, 0xa5, 0xa8, 0x82, 0x08, 0x52, 0x84, 0x7a, 0x81, 0x87, 0x34, 0x94, 0x36, 0x34, 0x44, 0x65,
	0x52, 0xc1, 0x13, 0x42, 0x9b, 0xdd, 0xe3, 0x64, 0x95, 0xcd, 0xce, 0x32, 0x33, 0x0e, 0xf8, 0x09,
	0x09, 0x09, 0x89, 0x37, 0x1e, 0x10, 0x12, 0x9f, 0x91, 0xcf, 0xc0, 0x03, 0x9a, 0xdb, 0x7a, 0xec,
	0xae, 0xdb, 0xd2, 0xf2, 0xe4, 0x9d, 0x73, 0xfd, 0x9d, 0xcb, 0x9c, 0x39, 0x86, 0xab, 0x19, 0x56,
	0x05, 0x1f, 0x7f, 0x97, 0xf2, 0x52, 0x09, 0x5e, 0x14, 0x28, 0xb6, 0x2a, 0xc1, 0x15, 0x27, 0x8b,
	0xe6, 0x47, 0xd2, 0xfb, 0xd0, 0xd9, 0x19, 0xa9, 0x13, 0x42, 0xa0, 0xa3, 0xc6, 0x15, 0xc6, 0xd1,
	0x46, 0xb4, 0xb9, 0xcc, 0xcc, 0x37, 0xb9, 0x01, 0x90, 0x0a, 0xcc, 0xb0, 0x54, 0x79, 0x52, 0xc4,
	0x2d, 0xc3, 0x09, 0x28, 0xf4, 0x01, 0xb4, 0x0f, 0x0f, 0x9f, 0x68, 0xd5, 0x8a, 0x0b, 0x65, 0x54,
	0x7b, 0xcc, 0x7c, 0x93, 0x0d, 0xe8, 0x24, 0x23, 0x75, 0x62, 0x94, 0xba, 0xdb, 0x17, 0xad, 0x53,
	0xb9, 0xa5, 0x5d, 0x31, 0xc3, 0xa1, 0x7b, 0xd0, 0x39, 0xe0, 0x19, 0x6a, 0xed, 0x32, 0x39, 0xab,
	0x1d, 0xeb, 0x6f, 0x72, 0x09, 0x5a, 0x79, 0xe5, 0x1c, 0xb6, 0xf2, 0x8a, 0x5c, 0x87, 0xb6, 0x94,
	0x27, 0x71, 0xdb, 0x18, 0xeb, 0x7a, 0x63, 0x87, 0x87, 0x4f, 0x98, 0xa6, 0xd3, 0x6f, 0x60, 0xe1,
	0x91, 0x10, 0x5c, 0x90, 0x2b, 0xb0, 0x28, 0x30, 0x91, 0xbc, 0x74, 0xd6, 0xdc, 0x49, 0xd3, 0x33,
	0x54, 0x49, 0xee, 0x83, 0x70, 0x27, 0x1d, 0xe0, 0x30, 0xff, 0xf1, 0x4b, 0x54, 0x27, 0x3c, 0x93,
	0xc6, 0xfc, 0x32, 0x0b, 0x28, 0xf4, 0x1e, 0xac, 0x3f, 0x47, 0xa9, 0x76, 0x79, 0x59, 0x62, 0xaa,
	0x72, 0x5e, 0x32, 0xfc, 0x7e, 0x84, 0xd2, 0x84, 0x57, 0xf2, 0xcc, 0x82, 0x0e, 0xc2, 0xd3, 0x01,
	0x31, 0xc3, 0xa1, 0x07, 0xb0, 0x3a, 0xab, 0x5a, 0x15, 0x63, 0x8d, 0xa4, 0x4a, 0xa4, 0xc4, 0xcc,
	0xa8, 0x2e, 0x31, 0x77, 0x22, 0xef, 0x42, 0x1b, 0x85, 0x70, 0xe9, 0xea, 0x79, 0x7b, 0x26, 0x2a,
	0xa6, 0x39, 0x74, 0x0f, 0xfa, 0xda, 0xfa, 0xee, 0x09, 0xa6, 0xa7, 0xbb, 0xbc, 0x1c, 0xe6, 0xc7,
	0xaf, 0x06, 0x41, 0xd6, 0x60, 0x41, 0xf0, 0x02, 0x65, 0xdc, 0xda, 0x68, 0x6f, 0x2e, 0x33, 0x7b,
	0xa0, 0x9f, 0xc3, 0x65, 0x63, 0x46, 0x0b, 0x4a, 0x1f, 0xd1, 0x87, 0x70, 0x21, 0x35, 0x66, 0x65,
	0x1c, 0x6d, 0xb4, 0x37, 0xbb, 0xdb, 0x57, 0x43, 0x7b, 0x81, 0x5b, 0xe6, 0xe5, 0xe8, 0x3e, 0xf4,
	0x43, 0x3b, 0x3a, 0xbc, 0x18, 0x2e, 0x24, 0x69, 0x8a, 0x95, 0xf2, 0xf1, 0xf9, 0xe3, 0xab, 0x03,
	0xdc, 0x81, 0x65, 0x63, 0x6d, 0x4f, 0xe1, 0x59, 0x63, 0x53, 0x6c, 0x40, 0x37, 0x43, 0x99, 0x8a,
	0xbc, 0xd2, 0xe9, 0x74, 0x95, 0x0c, 0x49, 0xf4, 0x97, 0x08, 0xfa, 0x5a, 0xdd, 0xd8, 0x61, 0x28,
	0x47, 0x85, 0x22, 0xb7, 0xa0, 0x93, 0x2b, 0x3c, 0x73, 0x49, 0xba, 0xec, 0x1d, 0xd7, 0xae, 0x98,
	0x61, 0xeb, 0xba, 0x48, 0x95, 0xa8, 0x91, 0xf4, 0x1d, 0x62, 0x4f, 0x1e, 0x76, 0x7b, 0x1e, 0x6c,
	0x8d, 0xb4, 0xe0, 0xc7, 0x32, 0xee, 0x58, 0xa4, 0xfa, 0x9b, 0xfe, 0x11, 0x05, 0xc5, 0x72, 0x38,
	0x06, 0xb0, 0xa4, 0x4b, 0x72, 0x30, 0x89, 0xaa, 0x3e, 0xbf, 0xb9, 0xf3, 0xf7, 0x61, 0x41, 0xa3,
	0xd7, 0xde, 0xa7, 0x4a, 0x36, 0x93, 0x04, 0x66, 0xa5, 0xe8, 0x5d, 0x18, 0x3c, 0x46, 0x15, 0xd6,
	0xcc, 0x70, 0x5d, 0x07, 0x0c, 0x60, 0xe9, 0x87, 0x5c, 0x9d, 0xec, 0x73, 0xd3, 0x02, 0xba, 0x78,
	0xf5, 0x99, 0xfe, 0x1c, 0x41, 0xdc, 0xa8, 0xea, 0x7a, 0xda, 0xc1, 0x8f, 0x9a, 0xe0, 0xb7, 0x5e,
	0x06, 0x5f, 0xe7, 0x40, 0xdf, 0xbc, 0xe6, 0x8e, 0xf3, 0xf0, 0x8d, 0x14, 0xbd, 0x03, 0x3d, 0xcd,
	0x79, 0xc6, 0x85, 0x62, 0x49, 0x79, 0x6c, 0x46, 0xc7, 0x50, 0xf0, 0x33, 0x3f, 0x78, 0xf4, 0xb7,
	0x1e, 0x1d, 0x8a, 0x1b, 0x9f, 0x3d, 0xd6, 0x52, 0x9c, 0x7e, 0x01, 0xf0, 0x14, 0xb1, 0x4a, 0x8a,
	0xfc, 0x1c, 0x33, 0xb2, 0x02, 0xed, 0xf3, 0xbc, 0x72, 0x38, 0xf5, 0x27, 0xb9, 0x0d, 0x2b, 0x25,
	0xaa, 0xbd, 0x52, 0xa1, 0x18, 0x26, 0xa9, 0xad, 0x8f, 0xad, 0xc2, 0x0b, 0x74, 0xba, 0x0d, 0x17,
	0xf7, 0x79, 0x92, 0x1d, 0x25, 0x45, 0x52, 0xa6, 0x28, 0xdc, 0x98, 0x8a, 0xea, 0x31, 0xe5, 0x07,
	0x61, 0x6b, 0x32, 0x08, 0xe9, 0x9f, 0x11, 0xac, 0x3d, 0x1d, 0x1d, 0xe1, 0xce, 0xb3, 0xbd, 0x43,
	0x14, 0xe7, 0x28, 0xdc, 0x44, 0x68, 0x1c, 0xb8, 0xdb, 0x00, 0xa7, 0x35, 0x58, 0x97, 0x38, 0xe2,
	0xb3, 0x32, 0x09, 0x83, 0x05, 0x52, 0xe4, 0x2e, 0x5c, 0x2c, 0x02, 0x50, 0xae, 0x5b, 0xd6, 0xbc,
	0x56, 0x08, 0x98, 0x4d, 0x49, 0xd2, 0xbf, 0x3b, 0xd0, 0xdb, 0x2d, 0x46, 0x52, 0x19, 0x50, 0x76,
	0xa2, 0x74, 0x53, 0x4b, 0x08, 0xfa, 0x34, 0x24, 0x91, 0x67, 0xb0, 0x76, 0xda, 0x10, 0x8d, 0xc3,
	0x7a, 0xad, 0xc6, 0xda, 0x20, 0xc3, 0x1a, 0x35, 0xc9, 0x03, 0xe8, 0x95, 0x61, 0x55, 0x5d, 0x00,
	0xeb, 0x61, 0x33, 0xd4, 0x4c, 0x36, 0x2d, 0x4b, 0x1e, 0x01, 0x68, 0xc2, 0x7e, 0x72, 0x84, 0x85,
	0xbf, 0x05, 0xb7, 0xea, 0x3b, 0x1e, 0xc6, 0x66, 0xec, 0x58, 0xb9, 0x47, 0xa5, 0x12, 0x63, 0x16,
	0x28, 0x92, 0xe7, 0xd0, 0xd7, 0xa7, 0x9d, 0xb2, 0xe4, 0x2a, 0xd1, 0xa3, 0x44, 0xc6, 0x0b, 0xc6,
	0xd6, 0xed, 0xf9, 0xb6, 0x02, 0x61, 0x6b, 0x70, 0xd6, 0x04, 0xd9, 0x84, 0x7e, 0x7e, 0x96, 0x1c,
	0x23, 0xc3, 0x8a, 0xcb, 0x5c, 0x71, 0x31, 0x8e, 0x17, 0x4d, 0x46, 0x67, 0xc9, 0xe4, 0x1a, 0x2c,
	0x57, 0x3c, 0x3b, 0x1c, 0x1d, 0x95, 0xa8, 0xe2, 0x0b, 0x46, 0x66, 0x42, 0x20, 0x37, 0xa1, 0x27,
	0x51, 0x9c, 0xe7, 0x29, 0x3a, 0x89, 0x25, 0x23, 0x31, 0x4d, 0x24, 0xef, 0xc1, 0x65, 0x9d, 0x5f,
	0x51, 0xa2, 0x42, 0xf9, 0x35, 0x0a, 0xa9, 0x87, 0xe4, 0xb2, 0x91, 0x7c, 0x91, 0x31, 0xf8, 0xd4,
	0x4e, 0xa8, 0x20, 0x21, 0xfa, 0x6e, 0x9c, 0xe2, 0xd8, 0xdf, 0x8d, 0x53, 0x1c, 0xeb, 0xe7, 0xe3,
	0x3c, 0x29, 0x46, 0xfe, 0x42, 0xd8, 0xc3, 0xfd, 0xd6, 0xdd, 0x68, 0xf0, 0x10, 0xd6, 0x9a, 0x72,
	0xf0, 0x6f, 0x6c, 0xd0, 0xc7, 0xb0, 0xf0, 0x3c, 0xc9, 0x4b, 0xf5, 0xba, 0x4a, 0x7a, 0xce, 0xe0,
	0x70, 0xa8, 0xbb, 0xcd, 0xbe, 0xd4, 0xee, 0x44, 0xff, 0x8a, 0x60, 0x45, 0xa3, 0xf9, 0xcc, 0xac,
	0x3a, 0x6f, 0xf7, 0x38, 0x92, 0x4f, 0x60, 0xb1, 0xb0, 0xdd, 0x64, 0x87, 0xd2, 0xcd, 0x50, 0x33,
	0xf4, 0xb0, 0x15, 0x36, 0x93, 0xd3, 0x21, 0xb7, 0x60, 0x51, 0xe9, 0x98, 0x7c, 0x2f, 0xd6, 0x53,
	0xcf, 0x44, 0xca, 0x1c, 0x73, 0x70, 0x0f, 0xba, 0x6f, 0x98, 0x79, 0xfa, 0x6b, 0x04, 0x3d, 0x0b,
	0xc3, 0xcf, 0xed, 0xfb, 0xd0, 0xd5, 0xf1, 0xec, 0x4e, 0xbd, 0xde, 0xf1, 0x3c, 0xd8, 0x2c, 0x14,
	0xd6, 0x97, 0x2f, 0x0d, 0x3b, 0xdb, 0xdd, 0xe3, 0xf5, 0xc6, 0xb6, 0x67, 0xd3, 0xb2, 0xf4, 0x09,
	0x74, 0x3d, 0x92, 0xb7, 0x7c, 0xfb, 0x3f, 0x82, 0x2b, 0x8f, 0x51, 0x79, 0x63, 0xaf, 0xfb, 0x28,
	0x95, 0x00, 0x56, 0xc5, 0xaf, 0x0c, 0xba, 0x82, 0x7e, 0x9e, 0xea, 0xef, 0xa9, 0x47, 0xb7, 0x35,
	0xf3, 0xe8, 0x7e, 0x00, 0xab, 0xc3, 0x24, 0x2f, 0x46, 0x02, 0x77, 0x93, 0xf2, 0x21, 0xee, 0x1d,
	0x97, 0x5c, 0x60, 0x66, 0x5a, 0x6b, 0x89, 0x35, 0xb1, 0xe8, 0xef, 0x11, 0xac, 0x4c, 0x1c, 0xba,
	0x77, 0x7d, 0x1b, 0x20, 0xab, 0x69, 0xae, 0xdb, 0xea, 0x91, 0x1d, 0x48, 0x07, 0x52, 0xff, 0xed,
	0xb2, 0xf1, 0x13, 0xac, 0xbd, 0x90, 0xbb, 0xb7, 0x7a, 0x95, 0xb7, 0xfc, 0x52, 0xd1, 0x9e, 0xee,
	0xa4, 0xd9, 0xd0, 0xdd, 0x56, 0xb1, 0xfd, 0x5b, 0x1b, 0xfa, 0x75, 0x87, 0x29, 0xf3, 0x1f, 0x83,
	0x1c, 0xc0, 0xa5, 0xe9, 0xed, 0x97, 0x5c, 0xaf, 0x6f, 0x42, 0xd3, 0x42, 0x3d, 0x78, 0x67, 0x1e,
	0xbb, 0x2a, 0xc6, 0xf4, 0x7f, 0xe4, 0x21, 0xc0, 0x64, 0xf7, 0x20, 0xff, 0x9f, 0xda, 0xe2, 0xc2,
	0x35, 0x76, 0x70, 0xb5, 0x89, 0x65, 0x6d, 0x7c, 0x0b, 0xab, 0x0d, 0x2b, 0x0c, 0xa1, 0x5e, 0x63,
	0xfe, 0x6a, 0x34, 0xd8, 0x78, 0xa9, 0x8c, 0x35, 0xff, 0x31, 0x2c, 0xda, 0x2c, 0x90, 0xf5, 0xe9,
	0x8c, 0x79, 0x23, 0xab, 0xb3, 0x64, 0xab, 0xf7, 0x15, 0xf4, 0x67, 0xea, 0x47, 0x6e, 0x04, 0xee,
	0x1a, 0x2e, 0xc5, 0xe0, 0xda, 0x5c, 0xbe, 0x31, 0x79, 0x64, 0xff, 0xdb, 0xdd, 0xf9, 0x27, 0x00,
	0x00, 0xff, 0xff, 0xe8, 0xde, 0x96, 0xa9, 0xfd, 0x0d, 0x00, 0x00,
}
